### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by Pan-Qi** [UKPLab/ijcnlp2017-cmaps#1]
Hi I have some questions about the data.

![image](https://user-images.githubusercontent.com/43341456/60451352-32420080-9c6f-11e9-9a08-44c7664492cf.png)
I runned the program as the instruction, but the PipePrepocessing given the result as above.
Is that means we should put the documents in [file:/c:/monash/Knowledge%20graph/ijcnlp2017-cmaps/data/CMapSummaries/dummy/] ?

![image](https://user-images.githubusercontent.com/43341456/60451472-7a612300-9c6f-11e9-9db0-47a4ffa237a2.png)
In the instruction, it tells the data structure should be like this.
I'm wondering how we can get this structure data?
And can you supply any sample data?

Please give some instructions!
Thanks a lot!!!

**Comment by tbsflk** [comment]
Hi,

Sure, I can explain the data format a bit more.

Under the path that you created, ending in 'dummy', you can place a dataset. Since it's meant for mulit-document summarization, the expected format is a folder per set of documents to be summarized ('topic1', 'topic2', ... in the screenshot) in which the documents are placed as text files ending with '.txt'.

If you also want to train a new model, you should add the reference concept map in the same folder as a 'cmap'-file, which is simple a test file with 'concept\trelation\tconcept' triples per line.

If you try to run the code on single documents, simply put just a single file in each folder. Just make sure you have the folders, the code expects that.

The dataset used in the paper is here:
https://www.informatik.tu-darmstadt.de/ukp/research_6/data/summarization/concept_map_summaries/index.en.jsp

Hope that helps! Let me know if you have more questions.

**Comment by Pan-Qi** [comment]
Hi Tobias, 
Thanks for your explanation, the code is working well on your sample testing data now.

But I encountered another issue that, when I do perdiction on my own data, the concept-graph.cmap files are always empty.
![image](https://user-images.githubusercontent.com/43341456/60658578-d35ed000-9e96-11e9-8987-c20b92169d4e.png)
The data formate is like this. Cause the last step need a .cmap file for scoring, so I create an empty .cmap file to make sure the code can find a .cmap file.
All previous steps worked well, and the needed files created by the code.
![image](https://user-images.githubusercontent.com/43341456/60658813-52540880-9e97-11e9-8160-b5849be6cb85.png)
Is this because we used different topics, the pretrained model vocabulary dictionary can't recognize my  topics works?
Do I need to train another model?
If so, can you please give any instructions for training a new model? 

Thanks a lot!
With Regards!

**Comment by tbsflk** [comment]
Hi,

the trained model should not be an issue, it does not have a vocabulary, if I remember correctly, it does not use any lexical features like ngrams or the like. It should predict scores no matter what and the following steps will take whichever concept got the highest scores, no matter how low they are.

Looking at the code, I think this could the issue: [Here](https://github.com/UKPLab/ijcnlp2017-cmaps/blob/master/src/main/java/pipeline/PipelineSummary.java#L59) it loads the cmap-file containing the target concept map and uses it's size as the size limit for the map being created. Since in your case the file is empty, it will use 0 as maxConcepts and therefore produces empty files. If you comment out that lines 57-59, the code will whatever size is defined at the top of that file and it should work.

Let me know if that solves the issue.

Best,
Tobias

**Comment by Pan-Qi** [comment]
Hi, 

It's working well till now.
Thanks a lot!

Best,
PQ
